### ISSUE TITLE
./test_gym.sh 'NoneType' object has no attribute 'add'

### ISSUE THREAD

**Issue by iaroslav-ai** [tambetm/simple_dqn#20]
I tried fixing #19 by adding the missing arguments declaration from main.py. I copy pasted following in test_gym.py:

```
mainarg.add_argument("--start_epoch", type=int, default=0, help="Start from this epoch, affects exploration rate and names of saved snapshots.")
mainarg.add_argument("--train_steps", type=int, default=250000, help="How many training steps per epoch.")
```

and what I get is

```
./test_gym.sh snapshots/Breakout-v0_18.prm
[2016-05-24 10:07:42,957] Making new env: Breakout-v0
Loading weights from snapshots/Breakout-v0_18.prm
[2016-05-24 10:07:44,096] Clearing 4 monitor files from previous run (because force=True was provided)
[2016-05-24 10:07:44,113] Starting new video recorder writing to /home/iaroslav/simple_dqn/results/Breakout-v0/openaigym.video.0.15157.video000000.mp4
Traceback (most recent call last):
  File "src/test_gym.py", line 75, in <module>
    agent.play(args.num_episodes)
  File "/home/iaroslav/simple_dqn/src/agent.py", line 131, in play
    self.mem.add(action, reward, screen, terminal)
AttributeError: 'NoneType' object has no attribute 'add'
[2016-05-24 10:07:44,492] Finished writing results. You can upload them to the scoreboard via gym.upload('/home/iaroslav/simple_dqn/results/Breakout-v0')
```

I also tried console command [from here](https://gym.openai.com/evaluations/eval_glkKKInTm6GlmcOQRZuhQ), but the result is the same.

 Is it working as expected or is there a bug?

**Comment by tambetm** [comment]
Fixed in https://github.com/tambetm/simple_dqn/commit/6dd0506fca44ed8c6561dad1b5ea788ab6db5b22.

**Comment by iaroslav-ai** [comment]
Great, thanks for the fix!
