### ISSUE TITLE
Array is too big when I try to begin training

### ISSUE THREAD

**Issue by ashwinreddy** [tambetm/simple_dqn#21]
I'm using OpenAI gym, so I installed all the relevant dependencies.

After running `./train.sh Breakout-v0 --environment gym`, I get an error from python saying

```
[2016-06-11 22:19:58,709] Making new env: Breakout-v0
[2016-06-11 22:19:58,780] Using Gym Environment
Traceback (most recent call last):
  File "src/main.py", line 103, in <module>
    mem = ReplayMemory(args.replay_size, args)
  File "/home/ubuntu/Developer/OpenAI/simple_dqn/src/replay_memory.py", line 12, in __init__
    self.screens = np.empty((self.size, args.screen_height, args.screen_width), dtype = np.uint8)
ValueError: array is too big.
```

Not sure how to fix.

**Comment by tambetm** [comment]
You can decrease the replay memory size if your computer is short of RAM. For example add `--replay_size 500000` to command line.
