### ISSUE TITLE
AttributeError: 'numpy.ndarray' object has no attribute  'asnumpyarray'

### ISSUE THREAD

**Issue by Seraphli** [tambetm/simple_dqn#27]
I followed the setup instruction and when I tried to run the train script, it showed this error.

```
(.venv2)seraphli@seraphli-desktop:~/Github/simple_dqn$ ./train.sh Breakout-v0 --environment gym
[2016-07-01 17:39:30,631] Making new env: Breakout-v0
[2016-07-01 17:39:30,660] Using Gym Environment
[2016-07-01 17:39:30,661] Replay memory size: 1000000
/home/seraphli/Github/neon/.venv2/local/lib/python2.7/site-packages/skcuda/cublas.py:272: UserWarning: creating CUBLAS context to get version number
  warnings.warn('creating CUBLAS context to get version number')
[2016-07-01 17:39:31,061] Initialized NervanaGPU
[2016-07-01 17:39:31,127] Neon is highly optimized for Maxwell GPUs. Although you might get speedups over CPUs, note that you are running on a pre-Maxwell GPU and you might not experience the fastest performance. For faster performance using the Nervana Cloud contact info@nervanasys.com
[2016-07-01 17:39:31,127] Backend: gpu, RNG seed: None
[2016-07-01 17:39:31,273] Results are written to results/Breakout-v0.csv
[2016-07-01 17:39:31,273] Populating replay memory with 50000 random moves
[2016-07-01 17:40:25,576]   num_games: 202, average_reward: 1.485149, min_game_reward: 0, max_game_reward: 7
[2016-07-01 17:40:25,576]   last_exploration_rate: 1.000000, epoch_time: 54s, steps_per_second: 922
[2016-07-01 17:40:25,576] Epoch #1
[2016-07-01 17:40:25,576]  Training for 250000 steps
Traceback (most recent call last):
  File "src/main.py", line 142, in <module>
    agent.train(args.train_steps, epoch)
  File "/home/seraphli/Github/simple_dqn/src/agent.py", line 106, in train
    self.net.train(minibatch, epoch)
  File "/home/seraphli/Github/simple_dqn/src/deepqnetwork.py", line 172, in train
    self.callback.on_train(cost.asnumpyarray()[0,0])
AttributeError: 'numpy.ndarray' object has no attribute  'asnumpyarray'
```

**Comment by tambetm** [comment]
I just pushed fix in e623b7984f88b3526284428b9ae2610793ae60b3, suggested by @mingwugmail in #26. Just do `git pull`.
