### ISSUE TITLE
RuntimeError: Device 0 does not have CUDA compute capability 3.0 or greater

### ISSUE THREAD

**Issue by riccitensor** [tambetm/simple_dqn#50]
While training I am getting this (CUDA 8, Ubuntu 16.4):

```
(.venv2) gamer@gamer:~/neon/simple_dqn$ ./train.sh Breakout-v0 --environment gym
2017-10-25 12:51:47,305 PyCUDA Runtime error: cuInit failed: no CUDA-capable device is detected
No handlers could be found for logger "gym.envs.registration"
Traceback (most recent call last):
  File "src/main.py", line 104, in <module>
    net = DeepQNetwork(env.numActions(), args)
  File "/home/gamer/neon/simple_dqn/src/deepqnetwork.py", line 34, in __init__
    stochastic_round = args.stochastic_round)
  File "/home/gamer/neon/neon/backends/__init__.py", line 113, in gen_backend
    deterministic=deterministic)
  File "/home/gamer/neon/neon/backends/backend.py", line 468, in allocate_backend
    return Backend.backends[name](**kargs)
  File "/home/gamer/neon/neon/backends/nervanagpu.py", line 732, in __init__
    check_gpu.ensure_gpu_capability(device_id)
  File "/home/gamer/neon/neon/backends/util/check_gpu.py", line 73, in ensure_gpu_capability
    "capability 3.0 or greater")
RuntimeError: Device 0 does not have CUDA compute capability 3.0 or greater
Exception AttributeError: AttributeError("'NervanaGPU' object has no attribute 'ctx'",) in <bound method NervanaGPU.__del__ of <neon.backends.nervanagpu.NervanaGPU object at 0x7fddda953e50>> ignored
```
This https://github.com/tambetm/simple_dqn/issues/3 does not help.

check_gpu outputs:

> DISPLAY:neon:PyCUDA Runtime error: cuInit failed: no CUDA-capable device is detected
> DISPLAY:neon:0

**Comment by tambetm** [comment]
CUDA compute capability is different thing than CUDA version. You can see CUDA compute capabilities of different cards here: https://en.wikipedia.org/wiki/CUDA#GPUs_supported.

**Comment by riccitensor** [comment]
I have 1070gfx, which is rel. new and seems to be supported as "GTX 1070" (https://en.wikipedia.org/wiki/CUDA#GPUs_supported)

**Comment by tambetm** [comment]
Can you run any of the Neon examples (https://github.com/NervanaSystems/neon/tree/master/examples)? If you get the same error, you should post an issue to Neon repo.
