### ISSUE TITLE
Assertion Error

### ISSUE THREAD

**Issue by mcbrs1a** [tambetm/simple_dqn#52]
I can get Breakout to play succesfully, pong however gives me this, any suggestions?

./play.sh snapshots/pong_141.pkl --replay_size 10 --backend cpu

2017-11-27 13:08:31,419 Using old model serialization format. Serialized the model into new format
Traceback (most recent call last):
  File "src/main.py", line 117, in <module>
    net.load_weights(args.load_weights)
  File "/home/putz/neon/simple_dqn/src/deepqnetwork.py", line 189, in load_weights
    self.model.load_params(load_path)
  File "/home/putz/neon/neon/models/model.py", line 418, in load_params
    self.deserialize(load_obj(param_path), load_states=load_states)
  File "/home/putz/neon/neon/models/model.py", line 462, in deserialize
    l.set_params(ps)
  File "/home/putz/neon/neon/layers/layer.py", line 744, in set_params
    attr.set(pdict['params'][key])
  File "/home/putz/neon/neon/backends/nervanacpu.py", line 246, in set
    assert value.size == self.size
AssertionError

**Comment by tambetm** [comment]
This might be caused by incompatibility between model format and newer Neon versions. Unfortunately I cannot help with this as I'm not actively working with this codebase any more. But you are welcome to submit PR.
