### ISSUE TITLE
ValueError: backend must be one of ('cpu', 'mkl')

### ISSUE THREAD

**Issue by bin913** [tambetm/simple_dqn#54]
## # When I run every example, the following error always happened
[Powered by Stella]
Use -help for help screen.
Warning: couldn't load settings file: ./ale.cfg
Game console created:
  ROM file:  roms/breakout.bin
  Cart Name: Breakout - Breakaway IV (1978) (Atari)
  Cart MD5:  f34f08e5eb96e500e851a80be3277a56
  Display Format:  AUTO-DETECT ==> NTSC
  ROM Size:        2048
  Bankswitch Type: AUTO-DETECT ==> 2K

WARNING: Possibly unsupported ROM: mismatched MD5.
Cartridge_MD5: f34f08e5eb96e500e851a80be3277a56
Cartridge_name: Breakout - Breakaway IV (1978) (Atari)

Running ROM file...
Random seed is 0
2017-12-07 15:19:09,891 Using minimal action set with size 4
2017-12-07 15:19:09,891 Using ALE Environment
2017-12-07 15:19:09,891 Replay memory size: 1000000
Traceback (most recent call last):
  File "src/main.py", line 104, in <module>
    net = DeepQNetwork(env.numActions(), args)
  File "/home/oem/work/Git/simple_dqn/src/deepqnetwork.py", line 34, in __init__
    stochastic_round = args.stochastic_round)
  File "/home/oem/work/Git/neon/neon/backends/__init__.py", line 113, in gen_backend
    deterministic=deterministic)
  File "/home/oem/work/Git/neon/neon/backends/backend.py", line 471, in allocate_backend
    raise ValueError("backend must be one of (%s)" % (names,))
ValueError: backend must be one of ('cpu', 'mkl')

**Comment by tambetm** [comment]
I suspect you don't have GPU dependencies installed, see http://neon.nervanasys.com/docs/0.9.0/installation.html#optional-dependencies.
